max-code-line-without-empty-lines: 9
checkers:
  all: True
  missing_semicolons: False

spaces-style:
  before: [ '+', '-', '=', '*', '/', '%', '&', '|', '^', '<<', '>>', '>>>', '**', '&&', '||', '?', '==', '!=', '===', '!==', '<', '<=', '>', '>=', 'instanceof', 'in' ]
  no-before: [ ')', ']', ',', ';', '.' ]
  after: [ '+', '=', '*', '/', '%', '&', '|', '^', '<<', '>>', '>>>', '**', '&&', '||', '?', ':', '==', '!=', '===', '!==', '<', '<=', '>', '>=', 'instanceof', 'in' ]
  no-after: [ '(', '[', ';', '.' ]